name: Build Debian Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up deb structure
      run: |
        chmod +x script/setup-deb-structure.sh
        ./script/setup-deb-structure.sh

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper devscripts

    - name: Build Debian package
      run: |
        mkdir -p dist
        dpkg-deb --build Kaze dist/kaze-icon-theme_1.0_all.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kaze-icon-theme
        path: dist/

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Debian Package to Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/kaze-icon-theme_${{ github.ref_name }}_all.deb
        asset_name: kaze-icon-theme_${{ github.ref_name }}_all.deb
        asset_content_type: application/vnd.debian.binary-package
