name: Build Debian Package and Create Release

on:
  push:
    tags:
      - 'v*'  # Dispara o workflow quando uma tag no formato 'vX.X.X' é criada

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up deb structure
      run: |
        chmod +x script/setup-deb-structure.sh
        ./script/setup-deb-structure.sh

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper devscripts

    - name: Build Debian package
      run: |
        mkdir -p dist
        dpkg-deb --build Kaze dist/kaze-icon-theme_${{ github.ref_name }}_all.deb

    - name: Install dependencies (RPM)
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm

    - name: Build RPM package
      run: |
        chmod +x script/build-rpm.sh
        ./script/build-rpm.sh

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}  # Nome da tag (obrigatório)
        name: Release ${{ github.ref_name }}  # Nome da release (opcional)
        body: |  # Descrição da release (opcional)
          Esta é a versão ${{ github.ref_name }} do tema de ícones Kaze.
          - Adicionados novos ícones.
          - Corrigidos bugs de renderização.
        draft: false  # Define se a release é um rascunho (opcional)
        prerelease: false  # Define se a release é uma pré-release (opcional)
        files: |  # Lista de arquivos para anexar à release
          dist/kaze-icon-theme_${{ github.ref_name }}_all.deb
          dist/kaze-icon-theme-${{ github.ref_name }}-1.noarch.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
